image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    paths:
      - build
      - .gradle

test:
  stage: test
    script: gradle check
    cache:
      paths:
        - build
        - .gradle