image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test

build:
  stage: build
  script: bash ./gradlew assemble

test:
  stage: test
  script: bash ./gradlew check